### ISSUE TITLE
2.5.x release for SilverStripe 4.5.3

### ISSUE THREAD

**Issue by HJGreen** [silverstripe/cwp-recipe-cms#17]
Hi,

I was wondering whether it would be possible to tag a new release on the `2.5` branch which tracks [SilverStripe 4.5.3](https://github.com/silverstripe/recipe-cms/releases/tag/4.5.3)?

Thanks

**Comment by brynwhyman** [comment]
Hi @HJGreen, unfortunately there is no plan for another 2.5.x release at this stage. CWP version 2.5 is under support for "Critical bugfixes and critical security fixes" only. This is outlined in the [CWP recipe support timeline](https://www.cwp.govt.nz/working-with-cwp/releases/).

I'd recommend investigating an upgrade straight to CWP 2.6.0. Alternatively, you could look at using an [alternative module version (instructions)](https://www.cwp.govt.nz/developer-docs/en/2/how_tos/use_alternate_module_version).

I'm going to close this issue for now.
